name: CI/CD to AWS EC2 and S3

on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present

  deploy:
    name: Push to Ec2
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: deploy to ec2
        uses: easingthemes/ssh-deploy@main
        env:
          ssh_private_key: -----BEGIN RSA PRIVATE KEY-----MIIJKgIBAAKCAgEAxfMDPVo7CfrF3oUEBKZhgQGALC2EpyUoErTWMqAScv9rG95OkRJ2/jvux1MvCmyP3RI+Qq5gYpTp+si9xdpziVOIx+Hfv/yYpdCAwDBCoNEGpqPP9WMpHp7HQr99GBko0JFoBCcu9gOB5psaP1XKwAvWwZiIztEk/gpKZR/2eCSIQAazjhoGDqg07H4VHR0GQH9kvWlIjrXR8lXw+iwPjJStCqoeyFYFFArOWfE9f8lxXECehVdmu4+BM6ClurzMVBePI8zmBW7wlGoWUpEfhvXxC48xFwOq9KRQC/zRJVcgXnsXucCqMXEa8201MQyhmDtIXl4TH2q/JjWCVBAd89KmLIqHu3RlH02iwQb4Pnu4Ga1C91B6/Yv5cRRg+ka9SB7g6WiusvwL2Kkx+2Y4ledUFptFeAY25CV0X7n9yh457XRZOnSHWIZNV7lknZUZzAzJYkduHkO+yHLKoNIkrbj2HcN/J98pXUC9sTLzZuC1j8qNZ2N9624U3H9b3lLCl2veiv8lw+1eIMNEGsZJ1FvO4+INt5eYMFfqzITKD2N0chk9irn9rQnjgtsyX6y6VaY/wwut8dm2g896HWWwYfMeGmAwEnpxHXzZ+eUaNQOkTCfyKjFOx2vN/quujF5K0VAmHIvKYqflQb3oxFxPQwsHhJXV31u2EHE9T9dUIvkCAwEAAQKCAgEAjk0RkiRwds8hOcMzzUfypjP2+UtLpoDumuwHY+Nw/9ygGiupHV9Bzag2EnK5SWwby9gWjAchYR0eS1vOGRLepeU4WkEFgdXLwr/uHrtS2psJhfgTQpujbtDD/Db+bbmAftdZCEtG1jJVSvtLViaNl5urKgdGqi7twfaR3rqoi1vv2t82azxICHdhfHVzJje8S9eJCyVJtNX+dJDVqHLORsiG0TjU4j38bpkKGNx00o11AdWuX7siLkmOnxeorGKXHQjGrPzaiyNirb7KB1cua+4X97BboOjRGAebR9LaY1aL/X/N4Yogj2R49HAYogcrj+1mK/jDFH2/pm8nHtlrPZ4IfB8llLp958z74Mi0DrZyZ0/D/8QC+k2TKR2Yh/tq2cwcsUif1saTroYcTuBq71qSIT5imLAkKGUy4sTQ/HCLXOoqI1MFS7COWzp71Idd9fGCzoqWF9dSaauaxlPBnNG024nUxeJ6iUwodyWFjBIqihHrA/KSbhF6zQeNLF2N0I1svV6V4p1bnc6p4CTsPsqGp3j9ErmKxcRKunLxXd/wFCKQrRradLX02k0UZDj5VDjgMXcQhX+m1TqXUQC8+nxHTLEfcGtNrbe7NHtEdKHvjGB+n1dSMOIcvtEx9ojPIoT8wmtIZxPTbCDdo/JfyHItKe+F4rU9hkJTFUyExdECggEBAOTQMnO94I0+5tyIpkYoRl584Zk310vK6lUdDD//L8LVfCh0zsUZB1mKBEhORH/9ie+NOHa1nqiPqb+98ORIC9VQ2WBErkn8VSgq84bs9uXT9Iv50zznUM0fNYwQv3lo2xWpoI7h2z+hU8JvVauDaE/soI3b0/SmSSLcXShdG+tE8fqcDHU/+vMM0huFm0d3HLblmDE63FERN97XJezJsLODVNhC+E9wJfe2dTUq3z6EgF8XOgXADS9Bpd1/K+peYYTLTxUC6Rj5AHReBTVzQ86ICCGeFXlO3wYesj/6M+zp9P6HcVqXWjUiC9DlAb9EltXdp3HBx92oUj1FhCqt2p0CggEBAN14BtEc+y81Ssaet19MnJGz+BLDzIHNGFBHBwBET1O93QTxqzUdr45CLwDrbM0E483oPijjVpJUK6BfsbszNQJdf9UIQPT1HpSpZj24aRCfAgOj8RoNghsfhbJ6bOSlwjiHB+oWxa+FRyg8ou2zxCpNGSO/MvQirQlt/APiittIbXZyh5sWrUOuydpfPttPCwEm8mqOk+I07MCEVk/dMr+Ulow8t/zZEeU/KZ8wnJugwdyxVroeJE4PL5tPHp/+JZzXxji/97Tz5Ny/mAnJk9ORexLhYYOgVobVJn5WhcGQ4Hg0C6sHwbdLr1BqWa6s9/9tCQD6Ozf1BayCHnnZXQ0CggEABxylhM1xDlLXMCGbMXENBuDQzkdbDMMI145olBCldmPWUReYWa32eYT9rxWnsWa7A9Qa3i20+b5FY21O8HmAzKePqhtYY3pRV0dGfHofDnOxFSy1sR3reASxUGIw4WAt9xVnpSlF/EtSZCe7vPH/qwRK1T3w75i/izLYPmnudTiWYNi61mYfsbBDU5GqiuUb4l9uhJE0ydxEJUwApMR8FohNec9TEn0E4Rctu3JSsAnER7BcIFOg1UgwFJtgTQ+T7mG3WorVne4XYoaNmOS1RdUak5jrR/L4oaMQnUZ0mLeI4uRo1I0Bw8cEIQENNdm26nzSOInyYWRa8gaYHg97TQKCAQEAoJ1QjE1xWX5TuZIXuNSN5BlZ+vnnEefVDztDt4zS3w+d/9zoZoAd9pTHE+qpIFLAh287zVl6SmsirI9aDUKI2itG7w+qVDyErhngnThlcflvc4Zs75EGX3dP9e1Vlckk/uvm8H0NZ0rIHUVEgBFUXb1GUydx455WUbVjBMpCG9/+Ct3qvK4IgEJ9/5H9uv0rJO3C90Zpt67cWI5hLlBkYo53VEMgyA4BLXnOTLXrje5bShuOozIC8F2REBikRDIDwyi1iCiok6Ihw3pr4AVB4TjrwfiUSOp6dhSVcyB6prPUJzjPkXzxn2YTQcWvPsAQpzzDP+M6GU3ojIBda88Y7QKCAQEA4VZ2qpTjY1CPu+Dh5TW4lTKFqsgEAODU42T65LGZdvIGpWrauQQQcLZCFf6wQD/I2uxRa8RKaTsxxYp3ViTzOpvruVkLnL+dzsPt6J3SzTLIJjwjxOFKw0T2lv+XrPlYi0QwNALocMDapCdjXE5YRVf/BKbaa5vaYMaCvJSenIJSfmkQjdogQDz9Md3QqyZVOHjYI54TlaK7z6tmn6MsOH7BDKYGYq6AYfmyOOmYa4MaSrODfHkpqlUZg2PrFQzQlf0dskWnAnce91bkcZsXE1ztpGJ/T+u8ocf7oqYRiePb6vu+eZx6oFes/KCH/RRjMGNuMehC1M6Tp2s1RY1kiw==-----END RSA PRIVATE KEY-----
          source: "./"
          remote_host: ec2-52-9-4-155.us-west-1.compute.amazonaws.com
          remote_user: ec2-user
          target: "/home/ec2-user/dnd-4e"