name: CI/CD to AWS EC2 and S3

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    name: Push to Ec2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy to ec2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: './dnd-4e'
          SCRIPT_AFTER: |
            screen -r
            cd dnd-4e
            pkill -f node
            npm install
            npm run build
            npm run start
            sudo systemctl restart nginx