name: CI/CD to AWS EC2 and S3

on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present

  deploy:
    name: Push to Ec2
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: deploy to ec2
        uses: easingthemes/ssh-deploy@main
        env:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./"
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          target: "/home/ec2-user/dnd-4e"