name: CI/CD to AWS EC2 and S3

on:
  push:
    branches: [ production ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: build and upload astro
        uses: withastro/action@v0
        with:
          node-version: ${{ matrix.node-version }}

  deploy:
    needs: build
    name: Push to Ec2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy to ec2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: './dnd-4e'
          SCRIPT_AFTER: |
            cd dnd-4e
            npm run build
            npm run start
            sudo systemctl nginx restart